version: '3'

services:
  reverse-proxy:
    image: traefik
    command: --api --docker --docker.watch
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  books:
    build: ./books
    image: v/books
    labels:
      - "traefik.backend=books"
      - "traefik.frontend.rule=PathPrefixStrip:/book/"
  customers:
    build: ./customers
    image: v/customers
    labels:
      - "traefik.backend=customers"
      - "traefik.frontend.rule=PathPrefixStrip:/customer/"